dbfilename redis_queue.rdb
dir /home/seo_k/PP/kindergarten/config/pids
pidfile /home/seo_k/PP/kindergarten/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/seo_k/PP/kindergarten/config/redis_queue.acl
